### PR TITLE
added automatic adjustment of scene size

### PR DESCRIPTION
**Pull request by wohltat**
Hi, this is more of an experimental branch. This is to show what i meant in #4 with an automatic adaptation of the ray length.

It seems to work but probably you don't want to use it as it is. I just changed one `makeLine`. But i don't understand why there are multiple places with `makeLine` in `traceRay` and `redrawRay`

### CODE REVIEW

**Comment by chbergmann** [comment]
redrawRay() draws the first ray, or multiple first rays if it is a beam.
traceRay() takes the last ray and does the raytracing. It will call itself recursely for the last newly created ray

**Comment by chbergmann** [comment]
As I already mentioned I am happy with MaxRayLength = 1000000. But of course we can keep this as an option

**Comment by luzpaz** [comment]
What's the verdict on this?

**Comment by chbergmann** [comment]
I do not want to merge this pull request.
Adapting the ray length automatically to the size of the scene would confuse the users. We have the possibility to place an absorber box around our scene to set a limit.

**Pull request closed without merging**
