### PR TITLE
Dispersion feature

### PR DESCRIPTION
**Pull request by wohltat**
fixed the examples and added a new one for dispersion

### CODE REVIEW

**Comment by chbergmann** [comment]
you have forgotten to add the file examples/example_dispersion.py

**Comment by chbergmann** [comment]
If I run the 2D example, I get these errors:

18:31:27  <Exception> Quantity::operator -(): Unit mismatch in minus operation
18:31:27  Traceback (most recent call last):
  File "/home/christi/.FreeCAD/Mod/OpticsWorkbench/Ray.py", line 55, in execute
    self.redrawRay(fp)
  File "/home/christi/.FreeCAD/Mod/OpticsWorkbench/Ray.py", line 117, in redrawRay
    rgb = wavelen2rgb(fp.Wavelength)
  File "/home/christi/.FreeCAD/Mod/OpticsWorkbench/wavelength_to_rgb/gentable.py", line 58, in wavelen2rgb
    green = -(nm - 645.0) / (645.0 - 580.0)
<class 'ArithmeticError'>: {'sclassname': 'N4Base18UnitsMismatchErrorE', 'sErrMsg': 'Quantity::operator -(): Unit mismatch in minus operation', 'sfile': '', 'iline': 0, 'sfunction': '', 'swhat': 'Quantity::operator -(): Unit mismatch in minus operation', 'btranslatable': False, 'breported': True}
18:31:27  <Exception> Quantity::operator -(): Unit mismatch in minus operation
18:31:27  Traceback (most recent call last):
  File "/home/christi/.FreeCAD/Mod/OpticsWorkbench/Ray.py", line 55, in execute
    self.redrawRay(fp)
  File "/home/christi/.FreeCAD/Mod/OpticsWorkbench/Ray.py", line 117, in redrawRay
    rgb = wavelen2rgb(fp.Wavelength)
  File "/home/christi/.FreeCAD/Mod/OpticsWorkbench/wavelength_to_rgb/gentable.py", line 58, in wavelen2rgb
    green = -(nm - 645.0) / (645.0 - 580.0)
<class 'ArithmeticError'>: {'sclassname': 'N4Base18UnitsMismatchErrorE', 'sErrMsg': 'Quantity::operator -(): Unit mismatch in minus operation', 'sfile': '', 'iline': 0, 'sfunction': '', 'swhat': 'Quantity::operator -(): Unit mismatch in minus operation', 'btranslatable': False, 'breported': True}
18:31:27  <Exception> Quantity::operator -(): Unit mismatch in minus operation
18:31:27  {'sclassname': 'N4Base18UnitsMismatchErrorE', 'sErrMsg': 'Quantity::operator -(): Unit mismatch in minus operation', 'sfile': '', 'iline': 0, 'sfunction': '', 'swhat': 'Quantity::operator -(): Unit mismatch in minus operation', 'btranslatable': False, 'breported': True}

**Comment by chbergmann** [comment]
You can get rid of the error above if you cange App::PropertyLength to App::PropertyFloat in Ray.py line 47

**Comment by wohltat** [comment]
Ah damn, you are right. Wait a sec...

**Comment by wohltat** [comment]
I don't get errors with the PropertyLength, but i don't think it's absolutely necessary. I can change it but why are we seeing different behavior?

**Comment by wohltat** [comment]
> I can change it but why are we seeing different behavior?

Btw, which version of FC are you using?

**Pull request merged**
